### ISSUE TITLE
Can't get ctrl-x,ctr-f to work

### ISSUE THREAD

**Issue by rudvfaden** [lingo/sublime-fscompletion#13]
I can't get <kbd>ctrl-x,ctrl-f</kbd> to work.

**Comment by lingo** [comment]
Adding the following to your **Keybindings - User** file doesn't work?

```json
   { "keys": ["ctrl+x","ctrl+f"], "command": "file_system_comp_trigger"}
```

**Comment by rudvfaden** [comment]
Yes it works. Don't really remember what the problem was.

**Comment by lingo** [comment]
Glad it works for you!
